// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbm6QE4_TepJoRrNISUKqcX_GD48Bv78',
    appId: '1:703371350637:web:1c5a41274f801a66376564',
    messagingSenderId: '703371350637',
    projectId: 'planoo-436fc',
    authDomain: 'planoo-436fc.firebaseapp.com',
    storageBucket: 'planoo-436fc.firebasestorage.app',
    measurementId: 'G-2MC9P0ZKNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHNpqpJ_RoYTyAbyXmcEgnfICQDBxY5g',
    appId: '1:703371350637:android:acbcd59c7ad96082376564',
    messagingSenderId: '703371350637',
    projectId: 'planoo-436fc',
    storageBucket: 'planoo-436fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP9vADg2M6ReWXs7YKivzPiFyU7hXlkxY',
    appId: '1:703371350637:ios:994ea8e85102a43b376564',
    messagingSenderId: '703371350637',
    projectId: 'planoo-436fc',
    storageBucket: 'planoo-436fc.firebasestorage.app',
    iosBundleId: 'com.your1site.planoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP9vADg2M6ReWXs7YKivzPiFyU7hXlkxY',
    appId: '1:703371350637:ios:1e20cf05fb61d7dc376564',
    messagingSenderId: '703371350637',
    projectId: 'planoo-436fc',
    storageBucket: 'planoo-436fc.firebasestorage.app',
    iosBundleId: 'com.example.centro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJbm6QE4_TepJoRrNISUKqcX_GD48Bv78',
    appId: '1:703371350637:web:25dfe9a57d45166d376564',
    messagingSenderId: '703371350637',
    projectId: 'planoo-436fc',
    authDomain: 'planoo-436fc.firebaseapp.com',
    storageBucket: 'planoo-436fc.firebasestorage.app',
    measurementId: 'G-48FNXQNTBS',
  );

}